DocumentRoot "/var/www/html/_bases/base_<nome progetto>/public_html"
ServerName <nome progetto>.local
ServerAdmin marco.sottana@gmail.com

SSLEngine on
SSLCertificateFile /etc/ssl/certs/orisbroker.local.crt
SSLCertificateKeyFile /etc/ssl/private/orisbroker.local.key

ErrorLog /var/www/html/<nome progetto>/error.log
CustomLog /var/www/html/<nome progetto>/access.log combined

<Directory "/var/www/html/_bases/base_<nome progetto>/public_html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

# Usa PHP 7.4 per orisbroker
#SetHandler "proxy:fcgi://127.0.0.1:9000"


<IfModule mod_proxy.c>
    <IfModule mod_proxy_fcgi.c>
        ProxyPassMatch ^/(.*\.php(/.*)?)$ unix:/var/run/php/php8.3-fpm.sock|fcgi://localhost/var/www/html/<nome progetto>/public_html
    </IfModule>
</IfModule>